# use dynaconf -i config.settings list to validate the values
# TODO: 这里的配准最终会区分为  必须修改，可修改、不建议修改、不可修改。
# 必须修改:  放命令行参数，比如BIDS目录，结果目录
# 可修改： 修改后不会影响结果。比如集成的其他程序的安装目录
# 不建议修改： 改动会影响Pipeline的结果。比如会产生删除操作，修改原结果的操作，不能复现原来结果的操作。
# 不可修改： 为DeepPrep的保留变量，仅开发者可以改动。比如改动后Pipeline发生改变。

# TODO: 将 DEEPPREP_HOME FREESURFER_HOME FSL_HOME JAVA_HOME 配置到环境变量

# Source set
CPU_NUM = 16
GPU_MB = 11000
RAM_MB = 30000
IO_WRITE_MB = 100
IO_READ_MB = 200

AUTO_SCHEDULE = true  # wether or not to use auto schedule. (default: true)

# Warning: RECON_ONLY and BOLD_ONLY cant both to be set true.
RECON_ONLY = false  # wether or not to run recon workflow only. (defaul: false)（replaced by args）
BOLD_ONLY = false  # wether or not to run bold precessing workflow only. (defaul: false)（replaced by args）

# ### program set ###
# DeepPrep: version ==
DEEPPREP_HOME = "/home/anning/workspace/DeepPrep/deepprep"

# FreeSurfer: version == 7.2
FREESURFER_HOME = "/usr/local/freesurfer720"

# FastSurfer: version ==
FASTSURFER_HOME = "@format {this.DEEPPREP_HOME}/FastSurfer"

# FastCSR: version ==
FASTCSR_HOME = "@format {this.DEEPPREP_HOME}/FastCSR"

# SageReg: version ==
FEATREG_HOME = "@format {this.DEEPPREP_HOME}/FeatReg"
SAGEREG_HOME = "@format {this.DEEPPREP_HOME}/SageReg"

# c3d_affine_tool： version ==
RESOURCE_DIR = "@format {this.DEEPPREP_HOME}/resource"

# VoxelMorph: version ==
VXM_MODEL_PATH = "@format {this.DEEPPREP_HOME}/model/voxelmorph"
MNI152_BRAIN_MASK = "/usr/local/fsl/data/standard/MNI152_T1_2mm_brain_mask.nii.gz"

# JAVA: version ==
JAVA_HOME = "/usr/lib/jvm/java-11-openjdk-amd64"

## ### input dir set ###
BIDS_DIR = ""  # where to save runtime cache, e.g. log file（replaced by args）
#
## ### output dir set ###
SUBJECTS_DIR = ""  # where to save Recon result（replaced by args）
BOLD_PREPROCESS_DIR = ""  # where to save bold preprocess result（replaced by args）
WORKFLOW_CACHED_DIR = ""  # where to save runtime cache, e.g. log file（replaced by args）

# ### GPU set ###
DEVICE = "cuda"
# ### CPU set ###
FS_THREADS = 16  # default thereads for OpenMP and ITK

# ENVIRON

[smri]
RAWAVG = true

[smri.OrigAndRawavg]
CPU_NUM = 1
RAM_MB = 500

[smri.Segment]
CPU_NUM = 0
RAM_MB = 7500
GPU_MB = 8500

[smri.Noccseg]
CPU_NUM = 1
RAM_MB = 500

[smri.N4BiasCorrect]
# CPU_NUM = FS_THREADS // 2
RAM_MB = 500

[smri.TalairachAndNu]
CPU_NUM = 1
RAM_MB = 500

[smri.Brainmask]
CPU_NUM = 1
RAM_MB = 1000

[smri.UpdateAseg]
CPU_NUM = 1
RAM_MB = 500

[smri.Filled]
CPU_NUM = 1
RAM_MB = 500

[smri.FastCSR]
PARALLEL = 'on'
CPU_NUM = 2
RAM_MB = 7000
GPU_MB = 7000

[smri.WhitePreaparc1]
# CPU_NUM = FS_THREADS // 2
RAM_MB = 1500

[smri.InflatedSphere]
# CPU_NUM = FS_THREADS // 2
RAM_MB = 500

[smri.Sagereg]
CPU_NUM = 1
RAM_MB = 5000
GPU_MB = 4200

[smri.JacobianAvgcurvCortparc]
CPU_NUM = 1
RAM_MB = 500

[smri.WhitePialThickness1]
# CPU_NUM = FS_THREADS // 2
RAM_MB = 1500

[smri.Curvstats]
CPU_NUM = 1
RAM_MB = 250

[smri.BalabelsMult]
# CPU_NUM = FS_THREADS
RAM_MB = 1500

[smri.Cortribbon]
CPU_NUM = 1
RAM_MB = 1000

[smri.Parcstats]
CPU_NUM = 1
RAM_MB = 500

[smri.Aseg7]
# CPU_NUM = FS_THREADS // 2
RAM_MB = 800

[fmri]
ATLAS_SPACE = "MNI152_T1_2mm" # （replaced by args）
TASK = "rest"  # which data to be proprecessing（replaced by args）
PREPROCESS_TYPE = "rest"  # can be set to rest or task (default: None)（replaced by args）

[fmri.BoldSkipReorient]
NSKIP_FRAME = 0
THREADS = 1
CPU_NUM = 1
RAM_MB = 1000
GPU_MB = 0
IO_WRITE_MB = 20
IO_READ_MB = 40

[fmri.StcMc]
THREADS = 1
CPU_NUM = 0
RAM_MB = 1000
GPU_MB = 0
IO_WRITE_MB = 20
IO_READ_MB = 40

[fmri.Register]
THREADS = 1
CPU_NUM = 0
RAM_MB = 1000
GPU_MB = 0
IO_WRITE_MB = 20
IO_READ_MB = 40

[fmri.Mkbrainmask]
THREADS = 1
CPU_NUM = 0
RAM_MB = 1000
GPU_MB = 0
IO_WRITE_MB = 20
IO_READ_MB = 40

[fmri.VxmRegistraion]
THREADS = 1
CPU_NUM = 1
RAM_MB = 3000
GPU_MB = 2715
IO_WRITE_MB = 0
IO_READ_MB = 0

[fmri.VxmRegNormMNI152]
BATCH_SIZE = 16
THREADS = 1
CPU_NUM = 0
RAM_MB = 15000
GPU_MB = 4529
IO_WRITE_MB = 0
IO_READ_MB = 0

# Please do not make any modifications until you understand the purpose of these items！！！
[DANGER]
FORCE_RECON = false  # force to run the recon pipeline. (default: false)
CHEAR_BOLD_CACHE_DIR = false  # wether or not to clear the bold cache while finished. (defaul: false)

#[default]
#
#[development]
