# use dynaconf -i config.settings list to validate the values
# TODO 这里的配准最终会区分为  必须修改，可修改、不建议修改、不可修改。
# 必须修改:  放命令行参数，比如BIDS目录，结果目录
# 可修改： 修改后不会影响结果。比如集成的其他程序的安装目录
# 不建议修改： 改动会影响Pipeline的结果。比如会产生删除操作，修改原结果的操作，不能复现原来结果的操作。
# 不可修改： 为DeepPrep的保留变量，仅开发者可以改动。比如改动后Pipeline发生改变。

AUTO_SCHEDULE = true  # wether or not to use auto schedule. (default: true)

# Warning: RECON_ONLY and BOLD_ONLY cant both to be set true.
RECON_ONLY = false  # wether or not to run recon workflow only. (defaul: false)（replaced by args）
BOLD_ONLY = false  # wether or not to run bold precessing workflow only. (defaul: false)（replaced by args）

# ### program set ###
# DeepPrep: version ==
DEEPPREP_HOME = "/home/anning/workspace/DeepPrep/deepprep"

# FreeSurfer: version == 7.2
FREESURFER_HOME = "/usr/local/freesurfer720"

# FSL: version == 6.0
FSL_HOME = "/usr/local/fsl"

# FastSurfer: version ==
FASTSURFER_HOME = "@format {this.DEEPPREP_HOME}/FastSurfer"

# FastCSR: version ==
FASTCSR_HOME = "@format {this.DEEPPREP_HOME}/FastCSR"

# SageReg: version ==
FEATREG_HOME = "@format {this.DEEPPREP_HOME}/FeatReg"
SAGEREG_HOME = "@format {this.DEEPPREP_HOME}/SageReg"

# c3d_affine_tool： version ==
RESOURCE_DIR = "@format {this.DEEPPREP_HOME}/resource"

# VoxelMorph: version ==
VXM_MODEL_PATH = "@format {this.DEEPPREP_HOME}/model/voxelmorph"
MNI152_BRAIN_MASK = "/usr/local/fsl/data/standard/MNI152_T1_2mm_brain_mask.nii.gz"

# JAVA: version ==
JAVA_HOME = "/usr/lib/jvm/java-11-openjdk-amd64"

## ### input dir set ###
#BIDS_DIR = ""  # where to save runtime cache, e.g. log file（replaced by args）
#
## ### output dir set ###
#SUBJECTS_DIR = ""  # where to save Recon result（replaced by args）
#BOLD_PREPROCESS_DIR = ""  # where to save bold preprocess result（replaced by args）
#WORKFLOW_CACHED_DIR = ""  # where to save runtime cache, e.g. log file（replaced by args）

# ### GPU set ###
DEVICE = "cuda"
# ### CPU set ###
THREADS = 8  # default thereads


# ENVIRON

[smri]

[smri.OrigAndRawavg]
threads = 1

[fmri]
ATLAS_SPACE = "MNI152_T1_2mm" # （replaced by args）
TASK = ""  # which data to be proprecessing（replaced by args）
PREPROCESS_TYPE = ""  # can be set to rest or task (default: None)（replaced by args）


#[default]
#
#[development]

# Please do not make any modifications until you understand the purpose of these items！！！
FORCE_RECON = false  # force to run the recon pipeline. (default: false)
CHEAR_BOLD_CACHE_DIR = false  # wether or not to clear the bold cache while finished. (defaul: false)
