AUTO_SCHEDULE = true  # wether or not to use auto schedule. (default: true)

FORCE_RECON = false  # force to run the recon pipeline. (default: false)
CHEAR_BOLD_CACHE_DIR = false  # wether or not to clear the bold cache while finished. (defaul: false)

# Warning: RECON_ONLY and BOLD_ONLY cant both to be set true.
RECON_ONLY = false  # wether or not to run recon workflow only. (defaul: false)
BOLD_ONLY = false  # wether or not to run bold precessing workflow only. (defaul: false)

# ### program set ###
# DeepPrep: version ==
DEEPPREP_HOME = "/home/anning/workspace/DeepPrep/deepprep"

# FreeSurfer: version == 7.2
FREESURFER_HOME = "/usr/local/freesurfer720"

# FSL: version == 6.0
FSL_HOME = "/usr/local/fsl"

# FastSurfer: version ==
FASTSURFER_HOME = "@format {this.DEEPPREP_HOME}/FastSurfer"

# FastCSR: version ==
FASTCSR_HOME = "@format {this.DEEPPREP_HOME}/FastCSR"

# SageReg: version ==
FEATREG_HOME = "@format {this.DEEPPREP_HOME}/FeatReg"
SAGEREG_HOME = "@format {this.DEEPPREP_HOME}/SageReg"

# c3d_affine_tool： version ==
RESOURCE_DIR = "@format {this.DEEPPREP_HOME}/resource"

# VoxelMorph: version ==
VXM_MODEL_PATH = "@format {this.DEEPPREP_HOME}/model/voxelmorph"
MNI152_BRAIN_MASK = "/usr/local/fsl/data/standard/MNI152_T1_2mm_brain_mask.nii.gz"

# JAVA: version ==
JAVA_HOME = "/usr/lib/jvm/java-11-openjdk-amd64"

## ### input dir set ###
#BIDS_DIR = ""  # where to save runtime cache, e.g. log file
#
## ### output dir set ###
#SUBJECTS_DIR = ""  # where to save Recon result
#BOLD_PREPROCESS_DIR = ""  # where to save bold preprocess result
#WORKFLOW_CACHED_DIR = ""  # where to save runtime cache, e.g. log file

# ### GPU set ###
DEVICE = "cuda"
# ### CPU set ###
THREADS = 8  # default thereads


# ENVIRON

[smri]

[smri.OrigAndRawavg]
threads = 1

[fmri]
ATLAS_SPACE = "MNI152_T1_2mm"
TASK = "rest"  # which data to be proprecessing
PREPROCESS_TYPE = "rest"  # can be set to rest or task(default: rest)


#[default]
#
#[development]
